### ISSUE TITLE
[FEATURE] - RF014 - Manter perfil

### ISSUE THREAD

**Issue by vh-machado** [LabEsUFPA/meuEgresso#101]
## Origem

- Cliente 

## Motivação

Solicitado pelo cliente

## Descrição

Permitir que haja atualização/edição de dados da contas dos usuários (egresso, secretário e admin)

## Funcionalidades existentes que serão afetadas

* Funcionalidade do RF004 será melhorada

## Lista de Tarefas

* [x]  Criar rota de GET do usuário com NOME, USUÁRIO, EMAIL e NÍVEL DE ACESSO
* [x]  Criar rota de PUT do usuário NOME, USUÁRIO, EMAIL, SENHA e NÍVEL DE ACESSO
* [x] Testes

**Comment by MarcusLoureiro** [comment]
Rotas já haviam sido criadas na Sprint 01 e 02
