### ISSUE TITLE
[BUG] Matrícula está sendo obrigatória para usuários se cadastrarem

### ISSUE THREAD

**Issue by viniciusdev-br** [LabEsUFPA/meuEgresso#107]
## Origem

- Testes

## Descrição do bug

Existe uma obrigatoriedade no campo de matrícula, mas pode ter usuários que não possuem no de matrícula (pós-graduandos).Neste caso, o correto seria tirar a obrigatoriedade do campo.

![req_1-matricula_obrigatoria](https://github.com/LabEsUFPA/meuEgresso/assets/68855615/e77699be-d45c-4fd5-8c7f-c8799b0decda)

 - Device: Notebook
 - OS: Windows 11
 - Browser: Google Chrome

**Comment by jonas-al** [comment]
Está obrigatoriedade já foi retirada faz um tempinho, a correção já está presente na branch develop.
![issue](https://github.com/LabEsUFPA/meuEgresso/assets/72419151/38041ac5-c134-46fc-8cf3-8adfbebd7d02)
