### ISSUE TITLE
[BUG] Formulário veio com alguns campos pré-definidos nos inputs com dados do usuário que está cadastrando e não o cadastrado

### ISSUE THREAD

**Issue by viniciusdev-br** [LabEsUFPA/meuEgresso#108]
## Origem

- Testes

## Descrição do bug

Formulário veio com alguns campos pré-definidos nos inputs com dados do usuário que está cadastrando e não o cadastrado

![image](https://github.com/LabEsUFPA/meuEgresso/assets/68855615/cbc81f2c-721f-407b-9003-5f012ff0df90)

 - Device: Notebook
 - OS: Windows 11
 - Browser: Google Chrome

**Comment by machinebitezz** [comment]
Os inputs do screenshot estão azuis, tem certeza que esse auto-preenchimento não foi feito pelo navegador? Peço que teste novamente em outro navegador, dispositivo ou em uma aba anônima; 

Se for testar no mesmo navegador, não esquecer de limpar a cache, grato.
