### ISSUE TITLE
[FEATURE] Reformar checkbox de desejo para pós graduação.

### ISSUE THREAD

**Issue by viniciusdev-br** [LabEsUFPA/meuEgresso#109]
## Origem

- Testadores

## Motivação

Facilitar o entendimento do usuário

## Descrição

Há uma opção onde se tem a possibilidade de escolher marcar um checkbox “Deseja realizar pós graduação?”. Uma possível correção seria apenas tirar o ponto de interrogação e adicionar o texto “Desejo realizar pós graduação” ou
adicionar a legenda “Deseja realizar pós graduação?” e em seguida duas opções de checkbox com os labels “Sim” e “Não”.

![image](https://github.com/LabEsUFPA/meuEgresso/assets/68855615/60fac12b-2a18-4cde-96bf-15d6516afb44)

**Comment by MarcusLoureiro** [comment]
branch #117 corrigiu isso.
