### ISSUE TITLE
[BUG] Falta de aviso para campos obrigatórios

### ISSUE THREAD

**Issue by viniciusdev-br** [LabEsUFPA/meuEgresso#110]
## Origem

- [ ] Produção
- [ ] Homologação
- [x] Testes

## Descrição do bug

Nas informações adicionais ao final do formulário, alguns campos aparecem
como inválidos, se tentarmos salvar sem preenchê-los, mas não há nenhum
indicativo de obrigatoriedade neles

![image](https://github.com/LabEsUFPA/meuEgresso/assets/68855615/1ce1defa-0934-48fd-af4c-14ca4039c0d4)

 - Device: Notebook
 - OS: Windows 11
 - Browser: Google Chrome

**Comment by MarcusLoureiro** [comment]
BUG corrigido usando a branch #66
