### ISSUE TITLE
[BUG] Mesmo preenchendo todos os dados obrigatórios, está dando uma mensagem de erro ao tentar salvar o cadastro.

### ISSUE THREAD

**Issue by viniciusdev-br** [LabEsUFPA/meuEgresso#111]
## Origem

- Testes

## Descrição do bug

Mesmo preenchendo todos os dados obrigatórios, está dando uma mensagem
de erro ao tentar salvar o cadastro. O cadastro prossegue apenas se, após cadastrar
o perfil, realizar o login com o usuário e seguir para a página de cadastro. Vale
ressaltar que a mensagem de erro também não indica o motivo do erro.

![image](https://github.com/LabEsUFPA/meuEgresso/assets/68855615/1bae1b51-5968-4b30-8817-7205fedb1190)

 - Device: Notebook
 - OS: Windows 11
 - Browser: Google Chrome

**Comment by MarcusLoureiro** [comment]
Isso acontece quando há uma mudança na API e não foi dado mvn install e refeito o banco de dados. Foi testado na versão atual da develop e passou o cadastro normal com retorno de API STATUS 201.
