### ISSUE TITLE
[QUESTION] - Endereço banco de dados e outros

### ISSUE THREAD

**Issue by hawkilol** [LabEsUFPA/meuEgresso#114]
# Descrição

Abro essa issue para sugerir uma mudança no banco de dados/back-end em relação ao endereço do egresso/empresa, visto que atualmente para atualizar esse dado é necessário cadastrar uma nova entrada para ele no banco.

O ideal seria o banco guardar todos os endereços previamente ou passar essa responsabilidade para o back-end que deve checar se o endereço já existe no banco e assim atualizar o id, logo, caso contrário criar a nova entrada e atualizar o id para o egresso/empresa, de modo que a requisição do front-end possua apenas o nome da nova entrada.

[Edit]: Outras entradas no banco que possuem sua propria tabela sem valores pre definidos também tem esse impedimento.

**Comment by alverad-katsuro** [comment]
Foi realizado uma correção na logica ao salvar novos endereços
