### ISSUE TITLE
[BUG] Ao validar o usuário o título da tela de espera está incorreto "inFormações" 

### ISSUE THREAD

**Issue by Imunity** [LabEsUFPA/meuEgresso#120]
## Origem

- Testes

## Descrição do bug

Ao validar o usuário o título da tela de espera está sendo exibido com o texto ‘informações’’ escrito como “inFormações” na frase: “Suas inFormações estão sendo analisadas

 - Device: Notebook
 - OS: Windows 11
 - Browser: Google Chrome

**Comment by MarcusLoureiro** [comment]
Na última versão da develop a tela está assim:
![image](https://github.com/LabEsUFPA/meuEgresso/assets/70539396/b445b618-d2d1-4c8e-9a1e-cdf35f958d83)
BUG Fechado
