### ISSUE TITLE
[BUG] Erro ao logar sem limpar os cookies do aplicativo

### ISSUE THREAD

**Issue by Imunity** [LabEsUFPA/meuEgresso#121]
## Origem

- Testes

## Descrição do bug

Ao tentar fazer login, tive erro e só consegui acessar após limpar os cookies do aplicativo, haviam dois tokens lá

 - Device: Notebook
 - OS: Windows 11
 - Browser: Google Chrome

**Comment by jonas-al** [comment]
Provavelmente isso ocorreu pois havia algum token salvo de alguma versão anterior do front, peço por gentileza que ao rodar a aplicação você limpe os dados da cache do seu navegador.

**Comment by MarcusLoureiro** [comment]
Já aconteceu comigo. É preciso apagar o token duplicado da versão anterior do front e atualizar o ambiente do front-end e back-end. Atualize o ambiente e tente novamente.  Sempre dê um git pull para atualizar as branchs.
Para o front-end: 
No terminal com o diretório do projeto aberto.
1. cd frontend/
2. npm i ou npm install
3. npm run dev

Para o back-end:
No terminal com o diretório do projeto aberto.
1. cd backend/
2. mvn install, pois podem ocorrer mudanças na api.
3. docker-compose up --build
