### ISSUE TITLE
[BUG] obrigatoriedade equivocada

### ISSUE THREAD

**Issue by Imunity** [LabEsUFPA/meuEgresso#122]
## Origem

- Testes

## Descrição do bug

Existe uma obrigatoriedade no campo de matrícula, mas pode ter usuários que não possuem nº de matrícula(pós-graduandos).Neste caso o correto seria tirar  a obrigatoriedade do campo

![printError](https://github.com/LabEsUFPA/meuEgresso/assets/42749600/6859f18c-7a88-4b8b-8356-b3ca64c31fab)

 - Device: Notebook
 - OS: Windows 11
 - Browser: Google Chrome

**Comment by MarcusLoureiro** [comment]
Na última versão da develop esse problema já está sanano:
![image](https://github.com/LabEsUFPA/meuEgresso/assets/70539396/c4a0e768-3ccb-485f-9ffd-110c5e76f1b2)
