### ISSUE TITLE
[BUG] RF002 - Cadastro egresso

### ISSUE THREAD

**Issue by Imunity** [LabEsUFPA/meuEgresso#123]
## Origem

- Testes

## Descrição do bug

Formulário veio com alguns campos pré-definidos nos inputs de texto que não fazem sentido.

![printError](https://github.com/LabEsUFPA/meuEgresso/assets/42749600/286366bd-8f38-413e-afb6-c18568737c59)

 - Device: Notebook
 - OS: Windows 11
 - Browser: Google Chrome

**Comment by machinebitezz** [comment]
Este comportamento é o esperado, os campos são auto preenchidos com os dados inseridos no cadastro de usuário.

**Comment by MarcusLoureiro** [comment]
Alguns dados são inseridos diretamento do banco de dados para o cadastro do egresso. Como o nome e o email.  Isso é totalmente esperado pelo sistema. Para facilitar para o usuário na hora do cadastro.
