### ISSUE TITLE
[BUG] Incoerência formulário de cadastro

### ISSUE THREAD

**Issue by Imunity** [LabEsUFPA/meuEgresso#125]
## Origem

- Testes

## Descrição do bug

Nas informações adicionais ao final do formulário, alguns campos aparecem como inválidos se tentarmos salvar sem preenchê-los, mas não há nenhum indicativo de obrigatoriedade neles 

![printError](https://github.com/LabEsUFPA/meuEgresso/assets/42749600/f7d11618-f891-49b5-a33d-5dd8cb7b9a62)

 - Device: Notebook
 - OS: Windows 11
 - Browser: Google Chrome

**Comment by MarcusLoureiro** [comment]
BUG corrigido usando a branch #66
