### ISSUE TITLE
[BUG] Mensagem de erro inválida e vaga

### ISSUE THREAD

**Issue by Imunity** [LabEsUFPA/meuEgresso#126]
## Origem

- Testes

## Descrição do bug

Mesmo preenchendo todos os dados obrigatórios, está dando uma mensagem de erro ao tentar salvar. Vale ressaltar que a mensagem de erro também não indica o motivo do erro. 

![printError](https://github.com/LabEsUFPA/meuEgresso/assets/42749600/de1769f2-ba45-4fe7-b706-715eb3a1c79c)

 - Device: Notebook
 - OS: Windows 11
 - Browser: Google Chrome

**Comment by MarcusLoureiro** [comment]
Isso acontece quando há uma mudança na API e não foi dado mvn install e refeito o banco de dados. Foi testado na versão atual da develop e passou o cadastro normal com retorno de API STATUS 201.
