### ISSUE TITLE
[REFACTOR] Impedir logo no inicio o cadastro duplicado de perfil.

### ISSUE THREAD

**Issue by MarskyH** [LabEsUFPA/meuEgresso#146]
## Origem

- Homologação

## Descreva o refactor

O cadastro de perfil duplicado só é dado como erro ao finalizar o cadastro do egresso.

## Comportamento esperado

Impedir logo no cadastro de perfil para que o usuário não perca tempo.

**Comment by jonas-al** [comment]
Já está pronto!
