### ISSUE TITLE
[BUG] Informações iguais são considerados usuários diferentes.

### ISSUE THREAD

**Issue by MarskyH** [LabEsUFPA/meuEgresso#148]
## Origem

- Homologação

## Descreva o bug

Nome maiúsculo e minúsculo no cadastro, o back entende como usuários diferentes e ambos são cadastrados no banco..

## Como simular o bug

Passos para reproduzir o comportamento:
1. Cadastrar perfil com nome por exemplo: Marcele
2. Cadastrar perfil com nome por exempleo: marcele
3. usuários com nomes iguais, mas com upper e lower case.
4. Ambos são o "mesmo" usuário, mas são cadastrados.
5. Veja o erro.

## Comportamento esperado

Deve ser impedido o cadastro do mesmo usuário, mesmo que os nomes estejam diferentes.

**Comment by EudeMonteiro** [comment]
Bug corrigido, o sistema automaticamente converte os nomes para o mesmo padrão de _case_ e o atributo de email foi modificado para _unique_

![image](https://github.com/LabEsUFPA/meuEgresso/assets/73922540/7d4b5695-75f5-4391-9a0b-583ad289ddf0)
