### ISSUE TITLE
[REFACTOR] No campo “Faixa Salarial” se o egresso receber 1 salário mínimo ele se encaixa tanto em “1 salário mínimo” quanto em “1 a 2 salários mínimos".

### ISSUE THREAD

**Issue by viniciusdev-br** [LabEsUFPA/meuEgresso#188]
## Origem

- Testes

## Descrição

No campo “Faixa Salarial” se o egresso receber 1 salário mínimo ele se encaixa tanto em “1 salário mínimo” quanto em “1 a 2 salários mínimos".

![image](https://github.com/LabEsUFPA/meuEgresso/assets/68855615/236765b6-f137-4ba3-ab80-5eddacc266a1)

 - Device: Notebook
 - OS: Windows 11
 - Browser: Google Chrome

**Comment by Tsumioshino** [comment]
Closed by #244
