### ISSUE TITLE
[BUG] O campo “Área de Atuação” é um campo obrigatório, mas não possui indicação disso. 

### ISSUE THREAD

**Issue by viniciusdev-br** [LabEsUFPA/meuEgresso#189]
## Origem

- Testes

## Descrição do bug

O campo “Área de Atuação” é um campo obrigatório, mas não possui indicação disso. 

![image](https://github.com/LabEsUFPA/meuEgresso/assets/68855615/cfa894e7-910a-481b-83a0-75c835057de6)

 - Device: Notebook
 - OS: Windows 11
 - Browser: Google Chrome

**Comment by alverad-katsuro** [comment]
@viniciusdev-br em qual pagina atualização ou cadastro? Não esqueça de informar a pagina

**Comment by viniciusdev-br** [comment]
Cadastro de egresso
