### ISSUE TITLE
[FEATURE] Melhorias no Requisito pós-homologação

### ISSUE THREAD

**Issue by Tsumioshino** [LabEsUFPA/meuEgresso#201]
## Origem

-  Cliente 
-  Analista de Requisito 

## Motivação

Alterações de requisitos feitas pelo líder da equipe de requisitos para suprir as demandas de correções ou outras que tenham sido levantadas durante a homologação do primeiro ciclo de desenvolvimento do projeto.

## Descrição

- RF001
   -<s>Caso seja realizado um cadastro de usuário admin, secretário ou egresso na tela de cadastro do administrador, a senha padrão deve ser **senhaPadrão123**</s>.
   
- RF002
  - Inclusão do campo **outros** para descrição do local da pós do egresso.
  - Campo **Tipo de bolsa** deve incluir **PROBAC**, **CAPES/CNPQ**;
  - Campo **Salário** deve ser alterado para incluir **1 salário mínimo**, **2 a 4 salários mínimos**, **5 a 10 salários mínimos**, **11 ou mais salários mínimos**;
  - Campo lista de **Local da pós-graduação** deve inserir campo **Outros** para o front-end consumir, e possibilitar inserir outras universidades.
  - Campo **Gênero** deve inserir campo **Não quero declarar**, e **Outros** para o front-end consumir, e possibilitar inserir outros gêneros.
  - Campo **Tipo de cota** deve incluir **PCD**.
  - Campo **Área de Atuação** deve incluir  **Programador** e  **Analista**.

## Funcionalidades existentes que serão afetadas

* Não se aplica

## Lista de Tarefas
* [x] <s>Alterar senha padrão do **usuário** (admin, secretário, egresso) criado pela "tela de cadastro admin" para **senhaPadrão123**</s>.
* [x] Alterar campos de gênero para capitalizado.
* [x] Campo **Tipo de bolsa** deve incluir **PROBAC**, **CAPES/CNPQ**;
* [x] Campo **Salário** deve ser alterado para incluir **1 salário mínimo**, **2 a 4 salários mínimos**, **5 a 10 salários mínimos**, **11 ou mais salários mínimos**;
* [x] Campo **Gênero** deve inserir campo **Não quero declarar**, e **Outros** para o front-end consumir, e possibilitar inserir outros gêneros.
* [x] Campo **Tipo de cota** deve incluir **PCD**.
* [x] Campo **Área de Atuação** deve incluir  **Programador** e  **Analista**.
* [x] Fazer atualizações correspondentes em data.sql e dump.sql
* [x] Ajuste de DTOs, caso necessário.
* [x] Ajuste de testes unitários, caso necessário.

**Comment by Tsumioshino** [comment]
- RF001
 - Para o primeiro acesso, a senha deverá ser gerada de forma randômica pelo sistema com base em alfanumérico de 8
caracteres, incluindo caracteres especiais, a ser informada somente no email de envio.
O reset da senha deve pedir uma senha com no mínimo oito dígitos, alfanumérica e com diferenciação entre
maísculas e minusculas. A alteração deve ser feita na tela de edição de cadastro.

*[ ] Gerar a senha de forma randômica utilizando sistema alfanumérico e com símbolos.
*[ ] Solicitar reset da senha no momento do login utilizando essa senha.

**Comment by Tsumioshino** [comment]
PR #244 fecha as tarefas referentes à inserção de dados.

**Comment by alverad-katsuro** [comment]
> * Para o primeiro acesso, a senha deverá ser gerada de forma randômica pelo sistema com base em alfanumérico de 8
>   caracteres, incluindo caracteres esp

ISSUE #277 tratou dessa funcionalidade

**Comment by Tsumioshino** [comment]
PR #283 fecha as tarefas referentes à recuperação de senha, utilizando formas mais robustas de segurança devido à ser um RNF.
