### ISSUE TITLE
[BUG] Na área do mapa ao visualizar um egresso, e navegar para ao lado até chegar no mesmo ponto o egresso já não está mais lá.

### ISSUE THREAD

**Issue by viniciusdev-br** [LabEsUFPA/meuEgresso#207]
## Origem

- Testes

## Descrição do bug

Campos de Carreira e Localização não aparecem mesmo sendo preenchidas como desempregado e Brazil/Pará/Belém

![image](https://github.com/LabEsUFPA/meuEgresso/assets/68855615/90977ef3-3ace-4cdc-a34f-5a5866818228)

![image](https://github.com/LabEsUFPA/meuEgresso/assets/68855615/1ad742da-63f0-4023-afe8-861251fb5c65)

 - Device: Notebook
 - OS: Windows 11
 - Browser: Google Chrome

**Comment by machinebitezz** [comment]
Corrigido em #205
