### ISSUE TITLE
[BUG] Ao aplicar zoom no mapa, a localização não aparece no ponto correto, aparecendo até mesmo na água.

### ISSUE THREAD

**Issue by viniciusdev-br** [LabEsUFPA/meuEgresso#208]
## Origem

- Testes

## Descrição do bug

Ao aplicar zoom no mapa, a localização não aparece no ponto correto, aparecendo até mesmo na água.

![image](https://github.com/LabEsUFPA/meuEgresso/assets/68855615/130e4917-9270-4019-84bd-c95ec188f04d)

 - Device: Notebook
 - OS: Windows 11
 - Browser: Google Chrome

**Comment by machinebitezz** [comment]
O problema é com os dados da API/Biblioteca de localização que estamos usando, pra resolver isso só usando uma API que converte nomes de cidades em coordenadas geográficas de maneira satisfatória.

**Comment by MarskyH** [comment]
Sandro informou dia 05/06/2023 que como a cliente não se disponibilizou recursos para uma api/biblioteca melhor. Então que fique a atual, pois a discrepância da localização não é grande.
