### ISSUE TITLE
[FEATURE] RF012 - Armazenamento 

### ISSUE THREAD

**Issue by MarskyH** [LabEsUFPA/meuEgresso#228]
## Origem

-  Cliente 

## Motivação

Ter backup dos dados

## Descrição

o sistema deve permitir backup em nuvem usando software livre ou hospedagem em servidores da ufpa

## Funcionalidades existentes que serão afetadas

* Não se aplica

## Lista de Tarefas

* [ ]  Criar Repository XXXXXXModel
* [ ]  Criar Interface Service XXXXXXModel
* [ ]  Implementar interface Service XXXXXXModel
* [ ]  Criar Controller XXXXXXModel

**Comment by alverad-katsuro** [comment]
Esse requisito não existe mais.
