### ISSUE TITLE
[BUG] Ao clicar em sair, o usuário não tem uma resposta do que está acontecendo

### ISSUE THREAD

**Issue by viniciusdev-br** [LabEsUFPA/meuEgresso#235]
## Origem

- Testes

## Descreva o bug

Ao clicar em sair, o usuário não tem uma resposta do que está acontecendo, na maioria das vezes simplesmente não sai.

**Comment by jonas-al** [comment]
No código presente na develop ao clicar em sair o usuário é redirecionando para o login.
Creio que esse seja o comportamento adequado, caso a equipe de teste tenha alguma sugestão de comportamento basta nos informar.
