### ISSUE TITLE
[BUG] Campos adicionais ao serem editados (RF004) não exibem modal de confirmação

### ISSUE THREAD

**Issue by viniciusdev-br** [LabEsUFPA/meuEgresso#238]
## Origem

- Testes

## Descreva o bug

Campos adicionais ao serem editados (Rf004) não exibem modal de confirmação para o usuário e às vezes nem são atualizados, só atualizam quando tento atualizar outra área do perfil (chamada de API não demonstra estar sendo feita para campos adicionar).

## Como simular o bug

Passos para reproduzir o comportamento:
1. Cadastrar um perfil com todos os campos possíveis
2. Editar apenas os campos adicionais do usuário

**Comment by hawkilol** [comment]
Após diversas tentativas não foi possível reproduzir o bug a partir dos passos listados, na branch develop.

**Comment by hawkilol** [comment]
Foi colateral de outros bugs já resolvidos na mesma branch
