### ISSUE TITLE
[BUG] Mal funcionamento na navegação com o header

### ISSUE THREAD

**Issue by viniciusdev-br** [LabEsUFPA/meuEgresso#240]
## Origem

- Testes

## Descreva o bug

Header ainda quebra misteriosamente ao clicar na logo para ir para home, depois clicar em editar perfil, ver perfil, home novamente.

**Comment by jonas-al** [comment]
Na minha revisão não consegui reproduzir esse bug...
Ficarei no aguardo de mais detalhes sobre o mesmo.
