### ISSUE TITLE
[BUG] Ao diminuir zoom do mapa, o mesmo fica pequeno ao ponto de ser coberto pelo background cinza

### ISSUE THREAD

**Issue by viniciusdev-br** [LabEsUFPA/meuEgresso#242]
## Origem

- Testes

## Descreva o bug

Ao diminuir zoom do mapa, o mesmo fica pequeno ao ponto de ser coberto pelo background cinza

![image](https://github.com/LabEsUFPA/meuEgresso/assets/68855615/49a7ee60-bce0-44a6-b23a-1a7120770146)

**Comment by alverad-katsuro** [comment]
Infelizmente por utilizarmos uma framework free, há algumas limitações tecnicas. Foi optado por deixar as bordas cinzas em pois a api Leaflet não calcula os pontos para duplicatas do mapa.

![image](https://github.com/LabEsUFPA/meuEgresso/assets/65864188/28a57363-008b-4919-8e47-f142fc83453a)

**Comment by viniciusdev-br** [comment]
Põe na conta que o pai paga

**Comment by alverad-katsuro** [comment]
kakaka
