### ISSUE TITLE
[BUG] Campo de Salário na vaga de emprego aceita valores não numéricos e não possui máscara monetário

### ISSUE THREAD

**Issue by ErrantCabral** [LabEsUFPA/meuEgresso#259]
## Origem

- Testes

## Descreva o bug

Ao cadastrar uma nova vaga de emprego, o campo de Salário aceita valores não numéricos e não possui máscara monetária

## Como simular o bug

Passos para reproduzir o comportamento:
1. No menu de cadastro de vaga
2. Informa valores não numéricos no campo Salário
3. Submeta o cadastro da vaga
4. E ele vai concluir o cadastro 

## Comportamento esperado

Deveria informar que o valor informado no campo de salário é invalido

## Imagens e/ou logs

![Screenshot_8](https://github.com/LabEsUFPA/meuEgresso/assets/105087721/05645737-51da-4989-85c9-d6775614d5da)

**Comment by Tsumioshino** [comment]
Corrigido na #247 no Back-End

**Comment by MarskyH** [comment]
Vou reforçar a nível de front-end
