### ISSUE TITLE
[BUG] Campo de Data de expiração na vaga de emprego aceita datas passadas 

### ISSUE THREAD

**Issue by ErrantCabral** [LabEsUFPA/meuEgresso#260]
## Origem

- Testes

## Descreva o bug

Ao cadastrar uma nova vaga de emprego, o campo de Data de expiração na vaga de emprego aceita datas passadas

## Como simular o bug

Passos para reproduzir o comportamento:
1. No menu de cadastro de vaga
2. Informa valores de datas já passadas no campo Data de Expiração
3. Submeta o cadastro da vaga
4. E ele vai concluir o cadastro 

## Comportamento esperado

Deveria informar que o valor informado no campo de data de expiração é invalido

## Imagens e/ou logs
![Screenshot_9](https://github.com/LabEsUFPA/meuEgresso/assets/105087721/e77b5502-deab-42aa-9d16-7e09a8ce544d)

**Comment by Tsumioshino** [comment]
Corrigido na #247 no Back-End

**Comment by MarskyH** [comment]
Vou reforçar a nível de front-end
