### ISSUE TITLE
[FEATURE] Recuperação de Senha

### ISSUE THREAD

**Issue by alverad-katsuro** [LabEsUFPA/meuEgresso#277]
## Origem

-  Arquiteto de Software

## Motivação

Permitir o usuário resetar a senha.

## Descrição

O usuário vai poder mudar a senha caso esqueça da mesma.

## Funcionalidades existentes que serão afetadas

* Não se aplica

## Lista de Tarefas
* [ ] Alterar ResponseType para emails que não existem no banco.

**Comment by alverad-katsuro** [comment]
Para quem for fazer o frontend.
Aqui temos a solicitação de recuperação de senha:
É necessário enviar somente o parâmetro redirect e o email como body no post.
![image](https://github.com/LabEsUFPA/meuEgresso/assets/65864188/c3e6fda6-7c9e-4f98-a1f6-75830d475e61)

* Se for valido ele ira enviar um email com o link de recuperação de senha.

![image](https://github.com/LabEsUFPA/meuEgresso/assets/65864188/e612d8ed-2c87-4ba5-b543-1377e72e4335)

*Obs: O link vai conter o parametro tokenAuth de autenticação para redefinir a senha em até 30m.

Por fim vai ser feito uma requisição contendo a senha no body no path a seguir.

Ex: localhost:15000/auth/recoveryPassowrd/asdsadasd-asdasdasd-as-dsadsadsa

![image](https://github.com/LabEsUFPA/meuEgresso/assets/65864188/c024b118-b157-49e0-a912-f7ff2b1cda29)

**Comment by Tsumioshino** [comment]
A funcionalidade de recuperar senha, para emails que não existem no banco, retorna um ResponseType positivo mesmo que devesse ser inválido. Dessa forma, atividade nova cadastrada para fazer.
