### ISSUE TITLE
[BUG] - Filtros não aparecem para usuários não logados.

### ISSUE THREAD

**Issue by MarskyH** [LabEsUFPA/meuEgresso#298]
## Origem

- Testes

## Descreva o bug

Filtros para visualizar vagas não aparecem para usuários não logados devido à falta de permissão no back-end.

## Como simular o bug

Passos para reproduzir o comportamento:
1. Esteja deslogado de qualquer conta.
2. Entre na página de visualizar anúncios.
3. Tente utilizar algum filtro

## Comportamento esperado

Os filtros de vaga deveriam aparecer independente de permissão.

## Imagens e/ou logs
![image](https://github.com/LabEsUFPA/meuEgresso/assets/68740186/29e24b2b-60d3-4c74-845c-5cc977768789)

**Comment by Tsumioshino** [comment]
![image](https://github.com/LabEsUFPA/meuEgresso/assets/68740186/2488c2cd-168e-43df-a961-34ab8f25324c)
