### ISSUE TITLE
[BUG] - Requisição não aceita ao cadastrar o perfil por causa do e-mail

### ISSUE THREAD

**Issue by MarskyH** [LabEsUFPA/meuEgresso#300]
## Origem
- Testes

## Descreva o bug

Ao cadastrar seu perfil para logar no sistema a requisição não é aceita imediatamente, porém ao tentar uma segunda vez ele diz que o usuário já existe. Então ao fazer login , o sistema aceita normalmente.

## Como simular o bug

Passos para reproduzir o comportamento:
1. Acesse a página de cadastre-se
2. Informe pelo menos os campos obrigatórios
3. Submeta o form 
4. Veja o erro

## Comportamento esperado

Notificar corretamente que o usuário foi aceito e redirecionar para para página de cadastro de egresso

## Imagens e/ou logs
![image](https://github.com/LabEsUFPA/meuEgresso/assets/70539396/42982eea-b5ca-42fa-963c-01d2da730a20)
![image](https://github.com/LabEsUFPA/meuEgresso/assets/70539396/93ba692c-f011-4b7d-9243-40c8d8b7b9af)

**Comment by alverad-katsuro** [comment]
@jonas-al 
@MarskyH 
Foi realizado a correção no backend

**Comment by MarskyH** [comment]
Resolvido
