### ISSUE TITLE
[BUG] - Não há redirecionamento para o perfil do egresso automático após terminar o cadastro de egresso

### ISSUE THREAD

**Issue by MarskyH** [LabEsUFPA/meuEgresso#304]
## Origem

- Testes

## Descreva o bug

Ao finalizar o cadastro de egresso ele é dado como correto, porém o usuário fica preso na mesma tela. precisando fazer logout e fazer login novamente

## Como simular o bug

Passos para reproduzir o comportamento:
1. Realizar cadastro de egresso
2. Enviar form
3. Veja o erro

## Comportamento esperado

Que haja o redirecionamento para para a tela de perfil

**Comment by machinebitezz** [comment]
Ja foi corrigido na branch de reestruturação do projeto.
