### ISSUE TITLE
[BUG] - Erro 500 ao não inserir matrícula e tentar atualizar dados duas vezes consecutivas.

### ISSUE THREAD

**Issue by MarskyH** [LabEsUFPA/meuEgresso#308]
## Origem

- Testes

## Descreva o bug

Erro 500 ao não inserir matrícula na parte acadêmica e tentar atualizar dados duas vezes consecutivas.

## Como simular o bug

Passos para reproduzir o comportamento:
1. Faça o cadastro de egresso sem matrícula
2. Vá para a página de editar perfil do egresso
3. Edite a parte acadêmica e salve sem inserir matrícula
4. Caso não ocorra o bug de primeira, tente mais uma vez
5. Veja o erro, e a cada outras duas vezes consecutivas ele sucede na edição e falha, caso não haja alterações na matrícula.

* [X] Frontend
  * [X] Matricula null caso vazia

**Comment by MarskyH** [comment]
Realizei alguns testes e não consegui reproduzir o bug:
![image](https://github.com/LabEsUFPA/meuEgresso/assets/70539396/044b98d0-0376-45f5-998d-c85587bbb032)
![image](https://github.com/LabEsUFPA/meuEgresso/assets/70539396/29eab84e-9ad3-45b7-a905-5e6426ad4fbc)
![image](https://github.com/LabEsUFPA/meuEgresso/assets/70539396/62ca4b85-c103-4d9d-bda3-878004d21581)

**Comment by Tsumioshino** [comment]
![image](https://github.com/LabEsUFPA/meuEgresso/assets/68740186/ba3e7ef5-5ce7-452d-8b5a-a54fa11ae69d)

![image](https://github.com/LabEsUFPA/meuEgresso/assets/68740186/6c760567-fc2c-4227-8aa5-59b75f853f13)

Talvez tenha condições prévias. Eu consegui reproduzir o bug novamente quando fazendo o cadastro de egressos sem matrícula, e depois tentando atualizar a parte acadêmica.

**Comment by hawkilol** [comment]
Esse erro 500 não foi relacionado a uma requisição errada do Front-End, O log da api retorna que a matricula tem que ser única, uma vez que já deve existir uma matricula vazia ('') no banco, então quando ele tenta atualizar ele acha a duplicata.

**Comment by Tsumioshino** [comment]
Foi corrigido à nivel de front enviando o valor nulo para inexistência de matrícula, evitando cadastro de string vazia; e, pois, de valores duplicata referente ao não cadastro de uma matrícula.
