### ISSUE TITLE
[BUG] - Edição não está ativa para admin/secretário.

### ISSUE THREAD

**Issue by MarskyH** [LabEsUFPA/meuEgresso#310]
## Origem

- Testes

## Descreva o bug

Editar cadastro logado como admin não aparecem as opções de edição

## Como simular o bug

Passos para reproduzir o comportamento:
1. Acessar painel do admin
2. Escolher um egresso e selecionar para editar cadastro
3. Veja o erro

## Comportamento esperado

Admin pode editar os dados dos egressos

## Imagens e/ou logs
![image](https://github.com/LabEsUFPA/meuEgresso/assets/70539396/d4c09459-b542-4cf2-9fda-d3d41752f735)

* [x] Frontend
* [x] Backend

**Comment by MarskyH** [comment]
Essa issue será tratada com a issue #318

**Comment by Tsumioshino** [comment]
A issue será retomada aqui para evitar confusões, e pelo fato de esta issue estar melhor documentada com informações.
