### ISSUE TITLE
[BUG] - Filtros da página de Atividades Recentes não funcionam em conjunto.

### ISSUE THREAD

**Issue by MarskyH** [LabEsUFPA/meuEgresso#315]
## Origem
- Homologação
- Testes

## Descreva o bug

Filtros da página de Atividades Recentes não funcionam em conjunto.

## Como simular o bug

Passos para reproduzir o comportamento:
1. Entrar na página de Atividades Recentes do dashboard de administrador
2. Tentar utilizar 2 ou mais filtros simultaneamente
3. Veja o erro

## Comportamento esperado

Os filtros deveriam funcionar em conjunto, similar à todo o restante do sistema que utiliza filtros.

**Comment by alverad-katsuro** [comment]
Corrigido em #316
