### ISSUE TITLE
[FEATURE] RF001 - Front-end - Tela de cadastro de perfil

### ISSUE THREAD

**Issue by jonas-al** [LabEsUFPA/meuEgresso#33]
## Origem

- Cliente 

## Motivação

O cliente pediu.

## Descrição

Tela de login e tela de cadastro de perfil.

## Funcionalidades existentes que serão afetadas

* Não se aplica

## Lista de Tarefas

* [x]  Criação da tela de login
* [x]  Criação da tela de cadastro de perfil
* [x] Testes Unitários
* [x] Integração
    * [x]  Autenticação do usuário
    * [x] Pré-cadastro do egresso
    * [x] Envio de informações para a validação do egresso
    * [x]  Cadastro do usuário pelo admin

**Comment by vh-machado** [comment]
Realizar integração entre back e front.
