### ISSUE TITLE
[REFACTOR] - Na tela de editar egresso Cotas do egresso indicam todas como obrigatórias

### ISSUE THREAD

**Issue by MarskyH** [LabEsUFPA/meuEgresso#335]
## Origem

- [ ] Produção
- [ ] Homologação
- [ ] Testes

## Descreva

Cotas do egresso indicam todas como obrigatórias, porém não deve ser assim. São opcionais, mesma coisa para bolsa.

## Como simular o bug

Passos para reproduzir o comportamento:
1. No menu x clique em '...'
2. Informa o valor x no campo '....'
3. Submeta o form '....'
4. Veja o erro

## Comportamento esperado

Uma descrição clara e concisa sobre o que deveria acontecer.

## Imagens e/ou logs
Se for o caso, adicione screenshots ou log *formatado* para ajudar na explicação do problema.

## Contexto adicional

Adicione qualquer outra informação útil.

## Possíveis soluções

Se aplicável, liste possíveis soluções para o problema

**Smartphone (please complete the following information):**

**Comment by Tsumioshino** [comment]
Issue #334 já abrange o escopo dessa issue.
