### ISSUE TITLE
[FEATURE] RF003 - Front-end - Tela de perfil

### ISSUE THREAD

**Issue by hawkilol** [LabEsUFPA/meuEgresso#34]
## Origem

- [x ] Cliente 

## Motivação

Pedido do cliente

## Descrição

Tela de perfil

## Funcionalidades existentes que serão afetadas

* Não se aplica

## Lista de Tarefas

* [x] Criação do header do perfil
* [x] Criação do body do perfil
* [x] Criação de botões para link
* [x] Criação de botões para edição
* [x] Configurar elementos na mesma pagina
* [x] Ajuste de layout
* [x] Testes Unitários
* [x] Tela de perfil Completa referente ao protótipo
* [x] Integração
    * [x] Consulta de dados cadastrados

**Comment by vh-machado** [comment]
Integração entre back-end e front-end:
- [ ] Consulta de dados cadastrados
