### ISSUE TITLE
[REFACTOR] - Admin pode aprovar o cadastro incompleto e não somente o pendente

### ISSUE THREAD

**Issue by MarskyH** [LabEsUFPA/meuEgresso#341]
## Origem

- Homologação

## Descreva

Cliente quer poder aprovar cadastros mesmo que estejam incompletos e/ou pendentes.
![image](https://github.com/LabEsUFPA/meuEgresso/assets/70539396/2e5e8ea2-a386-4c16-810b-df5eb0536208)

## Comportamento esperado
![image](https://github.com/LabEsUFPA/meuEgresso/assets/70539396/7fa490ce-002b-43c1-92c8-0669e58a9d70)
A opção de aprovar cadastro deve estar ativa para cadastros incompletos.

**Comment by vh-machado** [comment]
A implementação atual dos status está gerando inconsistências, por isso este refactor precisa ser reanalisado. Segue a proposta de novo fluxo para os status:
![fluxo-egressos-Proposta drawio](https://github.com/LabEsUFPA/meuEgresso/assets/73856054/92275028-ce8a-4aac-9b9b-cd4213f1b609)
