### ISSUE TITLE
[MELHORIA] - Inserir fotos dos usuários no feed de vagas

### ISSUE THREAD

**Issue by MarskyH** [LabEsUFPA/meuEgresso#349]
## Origem

-  Cliente 

## Motivação

Cliente pediu para que as fotos sejam inseridas nos cards com os anúncios de vaga

## Descrição

Foto no anúncio para ter um padrão entre as diferentes telas do sistema

## Funcionalidades existentes que serão afetadas
* Funcionalidade feed vagas será melhorada

## Lista de Tarefas
* [x]  Receber foto via back-end
* [x]  Inserir foto no front

**Comment by Tsumioshino** [comment]
![image](https://github.com/LabEsUFPA/meuEgresso/assets/68740186/5378a15f-a102-49c6-bada-28b642d9a39e)
Essa é a resposta que vem do back caso o usuário possua um egresso associado. Lembrando que um usuário que não é egresso pode cadastrar um anúncio, então os atributos de egresso e foto podem não vir no DTO dependendo de quem cadastrou. Também foi realizado a mudança para adaptar a mudança que foi realizada no createdBy, que deixou de retornar a estrutura de usuário, quebrando a integração referente à anúncios.
