### ISSUE TITLE
[MELHORIA] - Responsividade da página de Atividades Recentes pelo painel admin.

### ISSUE THREAD

**Issue by MarskyH** [LabEsUFPA/meuEgresso#355]
## Origem

-  Cliente 
-  Gerente de Projeto 
-  Analista de Requisito 
-  Arquiteto de Software
-  Desenvolvedores
-  Testadores

## Motivação

Descreva o por que você deseja essa funcionalidade.

## Descrição

Descrição da nova funcionalidade.

## Funcionalidades existentes que serão afetadas

* Funcionalidade exemplo um será alterada
* Funcionalidade exemplo dois será melhorada
* Funcionalidade exemplo três não será mais necessária
* Não se aplica

## Lista de Tarefas

* [ ]  Criar Repository XXXXXXModel
* [ ]  Criar Interface Service XXXXXXModel
* [ ]  Implementar interface Service XXXXXXModel
* [ ]  Criar Controller XXXXXXModel

**Comment by Tsumioshino** [comment]
Duplicate of #383
