### ISSUE TITLE
[BUG] E-mail de outro egresso possível de acessar um egresso qualquer

### ISSUE THREAD

**Issue by Tsumioshino** [LabEsUFPA/meuEgresso#366]
## Origem

- Testes

## Descreva o bug

O e-mail, considerado informação sensível no sistema, é mostrado à qualquer egresso que entrar no perfil de outro egresso e tentar entrar no próprio perfil.

## Como simular o bug

Passos para reproduzir o comportamento:
1. Logue em uma conta de egresso.
2. Entre no perfil público de outro egresso.
3. Tente retornar ao perfil do egresso logado pelo botão disponibilizado pelo front ao perfil.
4. Veja o erro

## Imagens e/ou logs
![image](https://github.com/LabEsUFPA/meuEgresso/assets/68740186/537fa296-566e-4ffe-b305-db9b523d0e44)
![image](https://github.com/LabEsUFPA/meuEgresso/assets/68740186/77ce95ce-11b6-40aa-a682-b0b2cedfe3f7)

**Comment by Tsumioshino** [comment]
Deixando claro que esse e-mail não é referente ao usuário mmo2001 que está logado, mas do egresso de nome "Nome Sobrenome". O back-end não deveria fornecer permissões necessárias para receber tais informações.

**Comment by EudeMonteiro** [comment]
Bug corrigido - EgressoDTO não possui mais o campo do usuário, portanto, não envia o email para o front-end
