### ISSUE TITLE
[MELHORIA] - Validação e-mail 

### ISSUE THREAD

**Issue by MarskyH** [LabEsUFPA/meuEgresso#369]
## Origem

-  Cliente 

## Motivação

Homologação ciclo 2

## Funcionalidades existentes que serão afetadas

* Funcionalidade de validação com e-mail será melhorada

**Comment by MarskyH** [comment]
Um regex pode ajudar a garantir e-mail com maior probabilidade de ser correto poderia ser :^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9-]+\.(?:com\.br|com|br)$

Testes:
![image](https://github.com/LabEsUFPA/meuEgresso/assets/70539396/3368f9a0-dc55-465f-abe3-d3ac63e8ff87)

**Comment by alverad-katsuro** [comment]
Resolvido em #300
