### ISSUE TITLE
[MELHORIA] Modal de envio de link para reset de senha sendo exibido para usuários que não tem email cadastrado na base de dados

### ISSUE THREAD

**Issue by viniciusdev-br** [LabEsUFPA/meuEgresso#413]
## Origem

- [X] Produção
- [ ] Homologação
- [ ] Testes

## Descreva o bug

Modal de envio de link para reset de senha sendo exibido para usuários que não tem email cadastrado na base de dados

## Como simular o bug

Passos para reproduzir o comportamento:
1. Entrar na página de login
2. Clicar em recuperar a senha
3. Digite um email aleatório que não esteja na base
4. Veja o modal de envio para o email

## Comportamento esperado

Informe de que o email não está cadastrado na base

## Imagens e/ou logs
![image](https://github.com/LabEsUFPA/meuEgresso/assets/68855615/a3433616-01ea-4052-af77-477077fb91f4)

**Comment by Tsumioshino** [comment]
Back-end: deve retornar um código de erro caso o e-mail não exista no banco.
Front-end: deve retornar um alerta ao usuário caso o e-mail não exista no banco.
