### ISSUE TITLE
[BUG] Retorno da requisição do mapa

### ISSUE THREAD

**Issue by MarskyH** [LabEsUFPA/meuEgresso#430]
## Origem
- Produção

## Descreva o bug

O retorno da requisição dos egressos para inserir no mapa do site está totalmente incorreta. Sendo assim o mapa deixa de ser renderizado por completo.

## Como simular o bug

Passos para reproduzir o comportamento:
1. Cadastre um perfil de egresso
2. Insira nele uma empresa e uma localização
3. Volte ao mapa
4. Veja o erro

## Comportamento esperado

O retorno ser ajustado para o que era antes

## Imagens e/ou logs
Requisição atual:
![image](https://github.com/LabEsUFPA/meuEgresso/assets/70539396/f5397d77-6a89-435f-8ec2-e255fdf7eaad)

O que o front esperava:
![image](https://github.com/LabEsUFPA/meuEgresso/assets/70539396/0c40e54f-b8cb-43b7-9a6e-3ce02223451e)

**Comment by alverad-katsuro** [comment]
Resolvido
