### ISSUE TITLE
[BUG] Perfil do Egresso Público não é construído caso ele possua endereço

### ISSUE THREAD

**Issue by Tsumioshino** [LabEsUFPA/meuEgresso#431]
## Origem

- Testes

## Descreva o bug

Perfil do Egresso Público não é construído caso ele possua endereço.

## Como simular o bug

1. Realize o cadastro de um egresso, colocando uma localização para o mesmo.
2. Deslogue da conta.
3. Acesse pela URL utilizando o ID do egresso.
4. Veja o erro

## Comportamento esperado

Perfil do Egresso Público deveria ser construído.

## Imagens e/ou logs
![image](https://github.com/LabEsUFPA/meuEgresso/assets/68740186/afbb23fb-6f1a-4605-9856-f0c142db7b50)
![image](https://github.com/LabEsUFPA/meuEgresso/assets/68740186/e70bd436-656c-4baf-a451-3e66b23f8c55)
![image](https://github.com/LabEsUFPA/meuEgresso/assets/68740186/4421909d-2b50-4905-ad75-8db0741ecc3d)

**Comment by Tsumioshino** [comment]
Lembrando que por mais que possa ter o caso de um perfil Pendente não ser construído, o bug se aplica mesmo se o administrador aprovar o mesmo.

**Comment by alverad-katsuro** [comment]
Resolvido
