### ISSUE TITLE
[BUG] Egresso sem localização aparecendo no mapa

### ISSUE THREAD

**Issue by MarskyH** [LabEsUFPA/meuEgresso#440]
## Origem

- Produção

## Descreva o bug

Egresso com localização, porém ao editar pelo admin diz que não há dados de localização.

## Como simular o bug

Passos para reproduzir o comportamento:
1. Faça login como admin
2. Acesse um perfil de um egresso pelo mapa
3. Vá até a sessão de localização
4. Veja o erro

## Imagens e/ou logs
Se for o caso, adicione screenshots ou log *formatado* para ajudar na explicação do problema.
![image](https://github.com/LabEsUFPA/meuEgresso/assets/70539396/3a63dc4d-c01b-4012-a17d-21d09166de8f)
![image](https://github.com/LabEsUFPA/meuEgresso/assets/70539396/9c1cb715-f1c3-4c59-a87f-67f7a4094238)

**Comment by Tsumioshino** [comment]
![image](https://github.com/LabEsUFPA/meuEgresso/assets/68740186/bed3aa63-856c-4b3c-8ce1-94ce39a4271a)
O back retorna os endereços. Provavelmente houve mudanças na estrutura de retorno do back-end que não foi notificada ao time de front-end, que ocasiounou a falha.

**Comment by alverad-katsuro** [comment]
Arrumado
