### ISSUE TITLE
[BUG]  Botões vazios no input de data que aumentam e diminuem o mês

### ISSUE THREAD

**Issue by viniciusdev-br** [LabEsUFPA/meuEgresso#454]
## Origem

- [ ] Produção
- [ ] Homologação
- [X] Testes

## Descreva o bug

Página de cadastro de dados do usuário: Botões vazios no input de data que aumentam e diminuem o mês, não deveria adicionar um ícone de + e -?

## Como simular o bug

Passos para reproduzir o comportamento:
1. Cadastrar um perfil
2. Validar email
3. Logar com o usuário
4. Abrir preenchimento de data

## Comportamento esperado

Íconde de + e - ou texto de avançar e voltar para o mês anterior

## Imagens e/ou logs
![image](https://github.com/LabEsUFPA/meuEgresso/assets/68855615/8847ec7a-6444-47ee-a5f0-5dfe104d8841)

**Comment by Tsumioshino** [comment]
Resolvido na #339
