### ISSUE TITLE
[BUG] Não é possível escolher um mês posterior ao mês de cadastro no input de datas

### ISSUE THREAD

**Issue by viniciusdev-br** [LabEsUFPA/meuEgresso#455]
## Origem

- [ ] Produção
- [ ] Homologação
- [X] Testes

## Descreva o bug

Não é possível escolher um mês posterior ao mês de cadastro no input de datas

## Como simular o bug

Passos para reproduzir o comportamento:
1. Cadastrar um perfil
2. Validar email
3. Logar com o usuário
4. Abrir preenchimento de data

## Comportamento esperado

O usuário deve poder escolher qualquer mês do ano

## Imagens e/ou logs
![image](https://github.com/LabEsUFPA/meuEgresso/assets/68855615/aa77e6d7-8e04-4f7c-9d48-cc1cdb763e76)

**Comment by Tsumioshino** [comment]
Isso não se configura como um bug. Foi solicitado pela Cliente que o Egresso deve possuir no mínimo 18 anos. Nesse caso, por esse teste ter sido feito no dia 29 de Junho de 2023, caso pudesse ser cadastrado de 30 de Junho de 2005 até datas posteriores, significa que o Egresso teria menos de 18 anos, o que se configuraria como Data não esperada pelo software.
