### ISSUE TITLE
[BUG] Interface PasswordEncoder não implementada e Variável passwordEncoder não instanciada

### ISSUE THREAD

**Issue by Tsumioshino** [LabEsUFPA/meuEgresso#74]
## Origem

- Testes

## Descreva o bug

Problemas na codificação do backend: não houve instanciação do passwordEncoder, o que faz ele ser nulo no momento de codificar a senha; e, pois, inutilizar a função de codificar a senha pelo serviço. 

## Como simular o bug

1. Criar um objeto de UsuarioModel e/ou UsuarioDTO;
2. Utilize a função save() do UsuarioServiceImpl para persistência de dados.

## Comportamento esperado

O esperado era que houvesse uma instanciação da interface PasswordEncoder na variável passwordEncoder, de tal forma que quando uma String qualquer fosse passada como um parâmetro do método encode, o texto da senha fosse codificado e o UsuarioModel e/ou UsuarioDTO fosse salvo no banco de dados.

## Imagens e/ou logs
![image](https://user-images.githubusercontent.com/68740186/234756809-aa24a2a3-4f42-467c-b335-10c4a5b58079.png)
![image](https://user-images.githubusercontent.com/68740186/234757372-2b0cd8ed-f3d2-4993-83f6-000cc38e1857.png)
![image](https://user-images.githubusercontent.com/68740186/234756934-7e152646-5186-41da-afbe-d785b8cd212e.png)

## Possíveis soluções

Utilizar uma implementação concreta da interface que codifique a senha de fato, e instanciar a classe em questão.

**Comment by alverad-katsuro** [comment]
![image](https://user-images.githubusercontent.com/65864188/235333104-0c2e1c54-904d-40b0-8bbb-2710ab973678.png)

Problemas na elaboração do teste.
