### ISSUE TITLE
[FEATURE] Adicionar métodos get em Egresso.

### ISSUE THREAD

**Issue by BrunoEiki** [LabEsUFPA/meuEgresso#82]
## Origem

- Desenvolvedores

## Motivação

Adicionar consultas para o controller do Egresso

## Descrição

Adicionar os métodos consultarEgressos, para retornar todos os egressos cadastrados no banco, e findByID, para retornar as informações de um egresso específico.

## Funcionalidades existentes que serão afetadas

* consultarEgressos
* findById

## Lista de Tarefas

* [ ]  Adicionar consultarEgressos
* [ ]  Adicionar findById

**Comment by Tsumioshino** [comment]
Duplicata de funcionalidade existente.
