### ISSUE TITLE
[FEATURE] RF023 - Cadastrar foto de perfil

### ISSUE THREAD

**Issue by chsantos234** [LabEsUFPA/meuEgresso#92]
## Origem

- Cliente 

## Motivação

Requisito proposto pelo cliente.

## Descrição

Desenvolvimento do armazenamento da imagem que será usada pelo usuário como foto de perfil.

## Funcionalidades existentes que serão afetadas

* Não se aplica

## Lista de Tarefas

* [x]  Função de armazenamento da imagem
* [x]  Função de retorno da imagem
* [x]  Mensagem de confirmação de upload da imagem

**Comment by chsantos234** [comment]
função de retorno da imagem está feita mas não funcionando corretamente

**Comment by Tsumioshino** [comment]
* [ ]  Testes Unitários
